[NavPoint { label: "Web前端黑客技术揭秘", content: "OEBPS/Text/0.xhtml", children: [], play_order: 1
    }, NavPoint { label: "序1", content: "OEBPS/Text/i.xhtml", children: [], play_order: 2
    }, NavPoint { label: "序2", content: "OEBPS/Text/ii.xhtml", children: [], play_order: 3
    }, NavPoint { label: "前言", content: "OEBPS/Text/iii.xhtml", children: [], play_order: 4
    }, NavPoint { label: "第一章 web安全的关键点", content: "OEBPS/Text/1.xhtml", children: [NavPoint { label: "1.1 数据与指令", content: "OEBPS/Text/1.1.xhtml", children: [], play_order: 6
            }, NavPoint { label: "1.2 浏览器的同源策略", content: "OEBPS/Text/1.2.xhtml", children: [], play_order: 7
            }, NavPoint { label: "1.3 信任与信任关系", content: "OEBPS/Text/1.3.xhtml", children: [], play_order: 8
            }, NavPoint { label: "1.4 社会工程学的作用", content: "OEBPS/Text/1.4.xhtml", children: [], play_order: 9
            }, NavPoint { label: "1.5 攻防不单一", content: "OEBPS/Text/1.5.xhtml", children: [], play_order: 10
            }, NavPoint { label: "1.6 场景很重要", content: "OEBPS/Text/1.6.xhtml", children: [], play_order: 11
            }, NavPoint { label: "1.7 小结", content: "OEBPS/Text/1.7.xhtml", children: [], play_order: 12
            }
        ], play_order: 5
    }, NavPoint { label: "第2章 前端基础", content: "OEBPS/Text/2.xhtml", children: [NavPoint { label: "2.1 W3C的世界法则", content: "OEBPS/Text/2.1.xhtml", children: [], play_order: 14
            }, NavPoint { label: "2.2 URL", content: "OEBPS/Text/2.2.xhtml", children: [], play_order: 15
            }, NavPoint { label: "2.3 HTTP协议", content: "OEBPS/Text/2.3.xhtml", children: [], play_order: 16
            }, NavPoint { label: "2.4 松散的HTML世界", content: "OEBPS/Text/2.4.xhtml", children: [], play_order: 17
            }, NavPoint { label: "2.5 跨站之魂——JavaScript", content: "OEBPS/Text/2.5.xhtml", children: [], play_order: 18
            }, NavPoint { label: "2.6 一个伪装出来的世界——CSS", content: "OEBPS/Text/2.6.xhtml", children: [], play_order: 19
            }, NavPoint { label: "2.7 另一个幽灵——ActionScript", content: "OEBPS/Text/2.7.xhtml", children: [], play_order: 20
            }
        ], play_order: 13
    }, NavPoint { label: "第3章 前端黑客之XSS", content: "OEBPS/Text/3.xhtml", children: [NavPoint { label: "3.1 XSS概述", content: "OEBPS/Text/3.1.xhtml", children: [], play_order: 22
            }, NavPoint { label: "3.2 XSS类型", content: "OEBPS/Text/3.2.xhtml", children: [], play_order: 23
            }, NavPoint { label: "3.3 哪里可以出现XSS攻击", content: "OEBPS/Text/3.3.xhtml", children: [], play_order: 24
            }, NavPoint { label: "3.4 有何危害", content: "OEBPS/Text/3.4.xhtml", children: [], play_order: 25
            }
        ], play_order: 21
    }, NavPoint { label: "第4章 前端黑客之CSRF", content: "OEBPS/Text/4.xhtml", children: [NavPoint { label: "4.1 CSRF概述", content: "OEBPS/Text/4.1.xhtml", children: [], play_order: 27
            }, NavPoint { label: "4.2 CSRF类型", content: "OEBPS/Text/4.2.xhtml", children: [], play_order: 28
            }
        ], play_order: 26
    }, NavPoint { label: "第5章 前端黑客之界面操作劫持", content: "OEBPS/Text/5.xhtml", children: [NavPoint { label: "5.1 界面操作劫持概述", content: "OEBPS/Text/5.1.xhtml", children: [], play_order: 30
            }, NavPoint { label: "5.2 界面操作劫持技术原理分析", content: "OEBPS/Text/5.2.xhtml", children: [], play_order: 31
            }, NavPoint { label: "5.3 界面操作劫持实例", content: "OEBPS/Text/5.3.xhtml", children: [], play_order: 32
            }, NavPoint { label: "5.4 有何危害", content: "OEBPS/Text/5.4.xhtml", children: [], play_order: 33
            }
        ], play_order: 29
    }, NavPoint { label: "第6章 漏洞挖掘", content: "OEBPS/Text/6.xhtml", children: [NavPoint { label: "6.1 普通XSS漏洞自动化挖掘思路", content: "OEBPS/Text/6.1.xhtml", children: [], play_order: 35
            }, NavPoint { label: "6.2 神奇的DOM渲染", content: "OEBPS/Text/6.2.xhtml", children: [], play_order: 36
            }, NavPoint { label: "6.3 DOM XSS挖掘", content: "OEBPS/Text/6.3.xhtml", children: [], play_order: 37
            }, NavPoint { label: "6.4 Flash XSS挖掘", content: "OEBPS/Text/6.4.xhtml", children: [], play_order: 38
            }, NavPoint { label: "6.5 字符集缺陷导致的XSS", content: "OEBPS/Text/6.5.xhtml", children: [], play_order: 39
            }, NavPoint { label: "6.6 绕过浏览器XSS Filter", content: "OEBPS/Text/6.6.xhtml", children: [], play_order: 40
            }, NavPoint { label: "6.7 混淆的代码", content: "OEBPS/Text/6.7.xhtml", children: [], play_order: 41
            }, NavPoint { label: "6.8 其他案例分享——Gmail Cookie XSS", content: "OEBPS/Text/6.8.xhtml", children: [], play_order: 42
            }
        ], play_order: 34
    }, NavPoint { label: "第7章 漏洞利用", content: "OEBPS/Text/7.xhtml", children: [NavPoint { label: "7.1 渗透前的准备", content: "OEBPS/Text/7.1.xhtml", children: [], play_order: 44
            }, NavPoint { label: "7.2 偷取隐私数据", content: "OEBPS/Text/7.2.xhtml", children: [], play_order: 45
            }, NavPoint { label: "7.3 内网渗透技术", content: "OEBPS/Text/7.3.xhtml", children: [], play_order: 46
            }, NavPoint { label: "7.4 基于CSRF的攻击技术", content: "OEBPS/Text/7.4.xhtml", children: [], play_order: 47
            }, NavPoint { label: "7.5 浏览器劫持技术", content: "OEBPS/Text/7.5.xhtml", children: [], play_order: 48
            }, NavPoint { label: "7.6 一些跨域操作技术", content: "OEBPS/Text/7.6.xhtml", children: [], play_order: 49
            }, NavPoint { label: "7.7 XSS Proxy技术", content: "OEBPS/Text/7.7.xhtml", children: [], play_order: 50
            }, NavPoint { label: "7.8 真实案例剖析", content: "OEBPS/Text/7.8.xhtml", children: [], play_order: 51
            }, NavPoint { label: "7.9 关于XSS利用框架", content: "OEBPS/Text/7.9.xhtml", children: [], play_order: 52
            }
        ], play_order: 43
    }, NavPoint { label: "第8章 HTML5安全", content: "OEBPS/Text/8.xhtml", children: [NavPoint { label: "8.1 新标签和新属性绕过黑名单策略", content: "OEBPS/Text/8.1.xhtml", children: [], play_order: 54
            }, NavPoint { label: "8.2 History API中的新方法", content: "OEBPS/Text/8.2.xhtml", children: [], play_order: 55
            }, NavPoint { label: "8.3 HTML5下的僵尸网络", content: "OEBPS/Text/8.3.xhtml", children: [], play_order: 56
            }, NavPoint { label: "8.4 地理定位暴露你的位置", content: "OEBPS/Text/8.4.xhtml", children: [], play_order: 57
            }
        ], play_order: 53
    }, NavPoint { label: "第9章 Web蠕虫", content: "OEBPS/Text/9.xhtml", children: [NavPoint { label: "9.1 Web蠕虫思想", content: "OEBPS/Text/9.1.xhtml", children: [], play_order: 59
            }, NavPoint { label: "9.2 XSS蠕虫", content: "OEBPS/Text/9.2.xhtml", children: [], play_order: 60
            }, NavPoint { label: "9.3 CSRF蠕虫", content: "OEBPS/Text/9.3.xhtml", children: [], play_order: 61
            }, NavPoint { label: "9.4 ClickJacking蠕虫", content: "OEBPS/Text/9.4.xhtml", children: [], play_order: 62
            }
        ], play_order: 58
    }, NavPoint { label: "第10章 关于防御", content: "OEBPS/Text/10.xhtml", children: [NavPoint { label: "10.1 浏览器厂商的防御", content: "OEBPS/Text/10.1.xhtml", children: [], play_order: 64
            }, NavPoint { label: "10.2 Web厂商的防御", content: "OEBPS/Text/10.2.xhtml", children: [], play_order: 65
            }, NavPoint { label: "10.3 用户的防御", content: "OEBPS/Text/10.3.xhtml", children: [], play_order: 66
            }, NavPoint { label: "10.4 邪恶的SNS社区", content: "OEBPS/Text/10.4.xhtml", children: [], play_order: 67
            }
        ], play_order: 63
    }
]
